anguage: node_js

node_js: stable

cache:
  directories:
  - node_modules
before_install:
  - npm install -g hexo-cli
  - npm install hexo-renderer-pug hexo-renderer-stylus --save

install:
  - npm install

script:
  - hexo clean
  - hexo g 

after_script:
  - git config user.name "yuexiliuli"
  - git config user.email "1614639905@qq.com"
  - sed -i "s/gh_token/${GH_TOKEN}/g" ./_config.yml
  - hexo deploy

branches:
  only:
    - blog-source

env:
  global:
    - GH_REF: github.com/yuexiliuli/yuexiliuli.github.io.git
  
notifications:
  email:
    - 1614639905@qq.com
  on_success: change
  on_failure: always
