# 文件路径 .github/workflows/deployment.yml
name: Deployment

# on:
#   push:
#     branches: [hexo] # only push events on source branch trigger deployment
  
# 当有 push 到仓库和外部触发的时候就运行
on: [push, repository_dispatch]


jobs:
  hexo-deployment:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai

    steps:
    - name: Checkout source
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Install dependencies & Generate static files
      env:
        YUQUE_TOKEN: ${{ secrets.YUQUE_TOKEN }}
      run: |
        node -v
        npm i -g hexo-cli
        npm install hexo-renderer-pug hexo-renderer-stylus --save
        npm install yuque-hexo --save 
        npm i -g yuque-hexo
        npm i --save-dev yuque-hexo
        npm i
        yuque-hexo sync
        hexo clean
        hexo g


    - name: Deploy to Github Pages
      env:
        GIT_NAME: yuexiliuli
        GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
        REPO: github.com/yuexiliuli/yuexiliuli.github.io
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        cd ./public && git init && git add .
        git config --global user.name $GIT_NAME
        git config --global user.email $GIT_EMAIL
        git commit -m "Site deployed by GitHub Actions"
        git push --force --quiet "https://$GH_TOKEN@$REPO" master:master